# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish version to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.1
        with:
          node-version: 12.18
      - uses: borales/actions-yarn@v2.3.0
      - run: yarn install --frozen-lockfile
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tagName = context.ref.replace(/\/refs\/tags\//, '');
            const versions = ['alpha', 'beta', 'latest', 'next']
            const whatIs = versions.filter(t => tagName.includes(t))
            return whatIs.join('') || 'latest'

      - name: Echo
        run: echo ${{ steps.tag.outputs.result }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.1
        with:
          node-version: 12.18
          registry-url: https://registry.npmjs.org/

      - run: yarn install --frozen-lockfile
      - run: npm publish --tag ${{ steps.tag.outputs.result }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
